- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  roles:
    - { role: openvpn, tags: openvpn }
    - { role: openvpn_client, tags: openvpn_client }
    - { role: revoke_openvpn_client, tags: revoke_openvpn_client }
