- name: set hostname using standard module
  hostname: name='{{ HOSTNAME }}'
  ignore_errors: true

- name: set hostname in /etc/hostname
  shell: 'echo {{ HOSTNAME }} > /etc/hostname'
  ignore_errors: true

# Updated playbook to include hostname in rc.local script
#  Ramesh - 5/4/2017
- name: set hostname in /etc/rc.local
  shell: 'echo hostname {{ HOSTNAME }} >> /etc/rc.local'
  ignore_errors: true

- name: set execute permission to rc.local script for centos 7
  shell: chmod +x /etc/rc.d/rc.local
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  args:
      warn: false

- name: set /etc/hosts file
  template: src=../templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
  with_items:
  - etc/hosts
  ignore_errors: true
